//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_TOP_Academy.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exam_TOP_Academy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Actions.
        /// </summary>
        public static string ActionsRecources {
            get {
                return ResourceManager.GetString("ActionsRecources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apply.
        /// </summary>
        public static string ApplyRecources {
            get {
                return ResourceManager.GetString("ApplyRecources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Authorization.
        /// </summary>
        public static string AuthorizationResources {
            get {
                return ResourceManager.GetString("AuthorizationResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Authors.
        /// </summary>
        public static string AuthorsRecources {
            get {
                return ResourceManager.GetString("AuthorsRecources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Before.
        /// </summary>
        public static string BeforeRecources {
            get {
                return ResourceManager.GetString("BeforeRecources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bestsellers.
        /// </summary>
        public static string BestsellersRecources {
            get {
                return ResourceManager.GetString("BestsellersRecources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ID.
        /// </summary>
        public static string BookIDRecources {
            get {
                return ResourceManager.GetString("BookIDRecources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BOOKKEEPING.
        /// </summary>
        public static string BookkeepingRecources {
            get {
                return ResourceManager.GetString("BookkeepingRecources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Book Title.
        /// </summary>
        public static string BookTitleResources {
            get {
                return ResourceManager.GetString("BookTitleResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Continue Without Login In.
        /// </summary>
        public static string ContinueWithoutLoginResources {
            get {
                return ResourceManager.GetString("ContinueWithoutLoginResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete book.
        /// </summary>
        public static string DeleteRecources {
            get {
                return ResourceManager.GetString("DeleteRecources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description.
        /// </summary>
        public static string DescriptionResources {
            get {
                return ResourceManager.GetString("DescriptionResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit book.
        /// </summary>
        public static string EditRecorces {
            get {
                return ResourceManager.GetString("EditRecorces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email.
        /// </summary>
        public static string EmailRersources {
            get {
                return ResourceManager.GetString("EmailRersources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        public static string EnterLoginResources {
            get {
                return ResourceManager.GetString("EnterLoginResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Existing Account?.
        /// </summary>
        public static string ExistingAccountResources {
            get {
                return ResourceManager.GetString("ExistingAccountResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на From.
        /// </summary>
        public static string FromRecources {
            get {
                return ResourceManager.GetString("FromRecources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Genre.
        /// </summary>
        public static string GenreRecources {
            get {
                return ResourceManager.GetString("GenreRecources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Help Me.
        /// </summary>
        public static string HelpMeResources {
            get {
                return ResourceManager.GetString("HelpMeResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You will be automatically logged in the app starts until you log in from somewhere else..
        /// </summary>
        public static string HintToolTipResources {
            get {
                return ResourceManager.GetString("HintToolTipResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login or Email.
        /// </summary>
        public static string InputLoginOrEmailResources {
            get {
                return ResourceManager.GetString("InputLoginOrEmailResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        public static string InputPasswordResources {
            get {
                return ResourceManager.GetString("InputPasswordResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language.
        /// </summary>
        public static string LanguageResources {
            get {
                return ResourceManager.GetString("LanguageResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        public static string LoginResources {
            get {
                return ResourceManager.GetString("LoginResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MAIN.
        /// </summary>
        public static string MainRecources {
            get {
                return ResourceManager.GetString("MainRecources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New Products.
        /// </summary>
        public static string NewProductsRecources {
            get {
                return ResourceManager.GetString("NewProductsRecources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pre-order.
        /// </summary>
        public static string Pre_orderRecources {
            get {
                return ResourceManager.GetString("Pre-orderRecources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Price.
        /// </summary>
        public static string PriceRecources {
            get {
                return ResourceManager.GetString("PriceRecources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Price.
        /// </summary>
        public static string PriceResources {
            get {
                return ResourceManager.GetString("PriceResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Publication Date.
        /// </summary>
        public static string PublicationDateResources {
            get {
                return ResourceManager.GetString("PublicationDateResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Publisher.
        /// </summary>
        public static string PublisherResources {
            get {
                return ResourceManager.GetString("PublisherResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Publishing Houses.
        /// </summary>
        public static string PublishingHousesRecources {
            get {
                return ResourceManager.GetString("PublishingHousesRecources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create Account.
        /// </summary>
        public static string RegisterOnResources {
            get {
                return ResourceManager.GetString("RegisterOnResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Registration.
        /// </summary>
        public static string RegistrationResources {
            get {
                return ResourceManager.GetString("RegistrationResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search for the author.
        /// </summary>
        public static string SearchAuthorsRecources {
            get {
                return ResourceManager.GetString("SearchAuthorsRecources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search for a publisher.
        /// </summary>
        public static string SearchPublisherRecources {
            get {
                return ResourceManager.GetString("SearchPublisherRecources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search.
        /// </summary>
        public static string SearchRecources {
            get {
                return ResourceManager.GetString("SearchRecources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sell book.
        /// </summary>
        public static string SellRecources {
            get {
                return ResourceManager.GetString("SellRecources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string SettingsResources {
            get {
                return ResourceManager.GetString("SettingsResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Status.
        /// </summary>
        public static string StatusRecources {
            get {
                return ResourceManager.GetString("StatusRecources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Keep me logged in.
        /// </summary>
        public static string StayOnlineResources {
            get {
                return ResourceManager.GetString("StayOnlineResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The title of the book.
        /// </summary>
        public static string TitleBookRecources {
            get {
                return ResourceManager.GetString("TitleBookRecources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Year publication.
        /// </summary>
        public static string YearPublicationRecources {
            get {
                return ResourceManager.GetString("YearPublicationRecources", resourceCulture);
            }
        }
    }
}
